// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: proto/communication.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageR_Status int32

const (
	MessageR_OK    MessageR_Status = 0
	MessageR_ERROR MessageR_Status = 1
)

// Enum value maps for MessageR_Status.
var (
	MessageR_Status_name = map[int32]string{
		0: "OK",
		1: "ERROR",
	}
	MessageR_Status_value = map[string]int32{
		"OK":    0,
		"ERROR": 1,
	}
)

func (x MessageR_Status) Enum() *MessageR_Status {
	p := new(MessageR_Status)
	*p = x
	return p
}

func (x MessageR_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageR_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_communication_proto_enumTypes[0].Descriptor()
}

func (MessageR_Status) Type() protoreflect.EnumType {
	return &file_proto_communication_proto_enumTypes[0]
}

func (x MessageR_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageR_Status.Descriptor instead.
func (MessageR_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_communication_proto_rawDescGZIP(), []int{1, 0}
}

type SubMessage_Status int32

const (
	SubMessage_OK    SubMessage_Status = 0
	SubMessage_ERROR SubMessage_Status = 1
)

// Enum value maps for SubMessage_Status.
var (
	SubMessage_Status_name = map[int32]string{
		0: "OK",
		1: "ERROR",
	}
	SubMessage_Status_value = map[string]int32{
		"OK":    0,
		"ERROR": 1,
	}
)

func (x SubMessage_Status) Enum() *SubMessage_Status {
	p := new(SubMessage_Status)
	*p = x
	return p
}

func (x SubMessage_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubMessage_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_communication_proto_enumTypes[1].Descriptor()
}

func (SubMessage_Status) Type() protoreflect.EnumType {
	return &file_proto_communication_proto_enumTypes[1]
}

func (x SubMessage_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubMessage_Status.Descriptor instead.
func (SubMessage_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_communication_proto_rawDescGZIP(), []int{3, 0}
}

type CommandR_Status int32

const (
	CommandR_OK    CommandR_Status = 0
	CommandR_ERROR CommandR_Status = 1
)

// Enum value maps for CommandR_Status.
var (
	CommandR_Status_name = map[int32]string{
		0: "OK",
		1: "ERROR",
	}
	CommandR_Status_value = map[string]int32{
		"OK":    0,
		"ERROR": 1,
	}
)

func (x CommandR_Status) Enum() *CommandR_Status {
	p := new(CommandR_Status)
	*p = x
	return p
}

func (x CommandR_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandR_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_communication_proto_enumTypes[2].Descriptor()
}

func (CommandR_Status) Type() protoreflect.EnumType {
	return &file_proto_communication_proto_enumTypes[2]
}

func (x CommandR_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandR_Status.Descriptor instead.
func (CommandR_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_communication_proto_rawDescGZIP(), []int{5, 0}
}

type SubAnnouncement_Status int32

const (
	SubAnnouncement_OK    SubAnnouncement_Status = 0
	SubAnnouncement_ERROR SubAnnouncement_Status = 1
)

// Enum value maps for SubAnnouncement_Status.
var (
	SubAnnouncement_Status_name = map[int32]string{
		0: "OK",
		1: "ERROR",
	}
	SubAnnouncement_Status_value = map[string]int32{
		"OK":    0,
		"ERROR": 1,
	}
)

func (x SubAnnouncement_Status) Enum() *SubAnnouncement_Status {
	p := new(SubAnnouncement_Status)
	*p = x
	return p
}

func (x SubAnnouncement_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubAnnouncement_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_communication_proto_enumTypes[3].Descriptor()
}

func (SubAnnouncement_Status) Type() protoreflect.EnumType {
	return &file_proto_communication_proto_enumTypes[3]
}

func (x SubAnnouncement_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubAnnouncement_Status.Descriptor instead.
func (SubAnnouncement_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_communication_proto_rawDescGZIP(), []int{6, 0}
}

type MessageS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token   string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *MessageS) Reset() {
	*x = MessageS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_communication_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageS) ProtoMessage() {}

func (x *MessageS) ProtoReflect() protoreflect.Message {
	mi := &file_proto_communication_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageS.ProtoReflect.Descriptor instead.
func (*MessageS) Descriptor() ([]byte, []int) {
	return file_proto_communication_proto_rawDescGZIP(), []int{0}
}

func (x *MessageS) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *MessageS) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type MessageR struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status MessageR_Status `protobuf:"varint,1,opt,name=status,proto3,enum=MessageR_Status" json:"status,omitempty"`
}

func (x *MessageR) Reset() {
	*x = MessageR{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_communication_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageR) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageR) ProtoMessage() {}

func (x *MessageR) ProtoReflect() protoreflect.Message {
	mi := &file_proto_communication_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageR.ProtoReflect.Descriptor instead.
func (*MessageR) Descriptor() ([]byte, []int) {
	return file_proto_communication_proto_rawDescGZIP(), []int{1}
}

func (x *MessageR) GetStatus() MessageR_Status {
	if x != nil {
		return x.Status
	}
	return MessageR_OK
}

type SubRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *SubRequest) Reset() {
	*x = SubRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_communication_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubRequest) ProtoMessage() {}

func (x *SubRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_communication_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubRequest.ProtoReflect.Descriptor instead.
func (*SubRequest) Descriptor() ([]byte, []int) {
	return file_proto_communication_proto_rawDescGZIP(), []int{2}
}

func (x *SubRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type SubMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  SubMessage_Status `protobuf:"varint,1,opt,name=status,proto3,enum=SubMessage_Status" json:"status,omitempty"`
	Message string            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SubMessage) Reset() {
	*x = SubMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_communication_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubMessage) ProtoMessage() {}

func (x *SubMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_communication_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubMessage.ProtoReflect.Descriptor instead.
func (*SubMessage) Descriptor() ([]byte, []int) {
	return file_proto_communication_proto_rawDescGZIP(), []int{3}
}

func (x *SubMessage) GetStatus() SubMessage_Status {
	if x != nil {
		return x.Status
	}
	return SubMessage_OK
}

func (x *SubMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CommandS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token   string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Command string   `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Args    []string `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
}

func (x *CommandS) Reset() {
	*x = CommandS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_communication_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandS) ProtoMessage() {}

func (x *CommandS) ProtoReflect() protoreflect.Message {
	mi := &file_proto_communication_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandS.ProtoReflect.Descriptor instead.
func (*CommandS) Descriptor() ([]byte, []int) {
	return file_proto_communication_proto_rawDescGZIP(), []int{4}
}

func (x *CommandS) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CommandS) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CommandS) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type CommandR struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  CommandR_Status `protobuf:"varint,1,opt,name=status,proto3,enum=CommandR_Status" json:"status,omitempty"`
	Message string          `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CommandR) Reset() {
	*x = CommandR{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_communication_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandR) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandR) ProtoMessage() {}

func (x *CommandR) ProtoReflect() protoreflect.Message {
	mi := &file_proto_communication_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandR.ProtoReflect.Descriptor instead.
func (*CommandR) Descriptor() ([]byte, []int) {
	return file_proto_communication_proto_rawDescGZIP(), []int{5}
}

func (x *CommandR) GetStatus() CommandR_Status {
	if x != nil {
		return x.Status
	}
	return CommandR_OK
}

func (x *CommandR) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SubAnnouncement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  SubAnnouncement_Status `protobuf:"varint,1,opt,name=status,proto3,enum=SubAnnouncement_Status" json:"status,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SubAnnouncement) Reset() {
	*x = SubAnnouncement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_communication_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubAnnouncement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubAnnouncement) ProtoMessage() {}

func (x *SubAnnouncement) ProtoReflect() protoreflect.Message {
	mi := &file_proto_communication_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubAnnouncement.ProtoReflect.Descriptor instead.
func (*SubAnnouncement) Descriptor() ([]byte, []int) {
	return file_proto_communication_proto_rawDescGZIP(), []int{6}
}

func (x *SubAnnouncement) GetStatus() SubAnnouncement_Status {
	if x != nil {
		return x.Status
	}
	return SubAnnouncement_OK
}

func (x *SubAnnouncement) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_communication_proto protoreflect.FileDescriptor

var file_proto_communication_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3a, 0x0a, 0x08, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x51, 0x0a, 0x08, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x12, 0x28, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x1b, 0x0a,
	0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12,
	0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01, 0x22, 0x22, 0x0a, 0x0a, 0x53, 0x75,
	0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x6f,
	0x0a, 0x0a, 0x53, 0x75, 0x62, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2a, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x53,
	0x75, 0x62, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x1b, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x06, 0x0a, 0x02,
	0x4f, 0x4b, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01, 0x22,
	0x4e, 0x0a, 0x08, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x53, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x61,
	0x72, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x22,
	0x6b, 0x0a, 0x08, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x12, 0x28, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x1b, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10,
	0x00, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01, 0x22, 0x79, 0x0a, 0x0f,
	0x53, 0x75, 0x62, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12,
	0x2f, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x17, 0x2e, 0x53, 0x75, 0x62, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x1b, 0x0a, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05,
	0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01, 0x32, 0x66, 0x0a, 0x0b, 0x43, 0x68, 0x61, 0x74, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x25, 0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x09, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53,
	0x1a, 0x09, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x22, 0x00, 0x12, 0x30, 0x0a,
	0x10, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x0b, 0x2e, 0x53, 0x75, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0b,
	0x2e, 0x53, 0x75, 0x62, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x30, 0x01, 0x32,
	0x37, 0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x25, 0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x12, 0x09, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x53, 0x1a, 0x09, 0x2e, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x22, 0x00, 0x32, 0x4c, 0x0a, 0x13, 0x41, 0x6e, 0x6e, 0x6f,
	0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x35, 0x0a, 0x10, 0x53, 0x65, 0x6e, 0x64, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x12, 0x0b, 0x2e, 0x53, 0x75, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x10, 0x2e, 0x53, 0x75, 0x62, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x22, 0x00, 0x30, 0x01, 0x42, 0x08, 0x5a, 0x06, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_communication_proto_rawDescOnce sync.Once
	file_proto_communication_proto_rawDescData = file_proto_communication_proto_rawDesc
)

func file_proto_communication_proto_rawDescGZIP() []byte {
	file_proto_communication_proto_rawDescOnce.Do(func() {
		file_proto_communication_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_communication_proto_rawDescData)
	})
	return file_proto_communication_proto_rawDescData
}

var file_proto_communication_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_proto_communication_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_communication_proto_goTypes = []interface{}{
	(MessageR_Status)(0),        // 0: MessageR.Status
	(SubMessage_Status)(0),      // 1: SubMessage.Status
	(CommandR_Status)(0),        // 2: CommandR.Status
	(SubAnnouncement_Status)(0), // 3: SubAnnouncement.Status
	(*MessageS)(nil),            // 4: MessageS
	(*MessageR)(nil),            // 5: MessageR
	(*SubRequest)(nil),          // 6: SubRequest
	(*SubMessage)(nil),          // 7: SubMessage
	(*CommandS)(nil),            // 8: CommandS
	(*CommandR)(nil),            // 9: CommandR
	(*SubAnnouncement)(nil),     // 10: SubAnnouncement
}
var file_proto_communication_proto_depIdxs = []int32{
	0,  // 0: MessageR.status:type_name -> MessageR.Status
	1,  // 1: SubMessage.status:type_name -> SubMessage.Status
	2,  // 2: CommandR.status:type_name -> CommandR.Status
	3,  // 3: SubAnnouncement.status:type_name -> SubAnnouncement.Status
	4,  // 4: ChatService.SendMessage:input_type -> MessageS
	6,  // 5: ChatService.SubscribeMessage:input_type -> SubRequest
	8,  // 6: CommandService.SendCommand:input_type -> CommandS
	6,  // 7: AnnouncementService.SendAnnouncement:input_type -> SubRequest
	5,  // 8: ChatService.SendMessage:output_type -> MessageR
	7,  // 9: ChatService.SubscribeMessage:output_type -> SubMessage
	9,  // 10: CommandService.SendCommand:output_type -> CommandR
	10, // 11: AnnouncementService.SendAnnouncement:output_type -> SubAnnouncement
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_communication_proto_init() }
func file_proto_communication_proto_init() {
	if File_proto_communication_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_communication_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_communication_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageR); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_communication_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_communication_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_communication_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_communication_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandR); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_communication_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubAnnouncement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_communication_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_communication_proto_goTypes,
		DependencyIndexes: file_proto_communication_proto_depIdxs,
		EnumInfos:         file_proto_communication_proto_enumTypes,
		MessageInfos:      file_proto_communication_proto_msgTypes,
	}.Build()
	File_proto_communication_proto = out.File
	file_proto_communication_proto_rawDesc = nil
	file_proto_communication_proto_goTypes = nil
	file_proto_communication_proto_depIdxs = nil
}
